/******************************************************************************
 *  Project    : MuroSync
 *  File       : murosync_build_info.h
 *  Created    : 2026-01-20
 *  Author     : Mikhail Vasilev
 *
 *  Description:
 *  Auto-generated firmware build/version metadata.
 *
 *  This file is generated by: cmd\gen_murosync_build_info.bat
 *  Do not edit manually.
 *
 *  Copyright (c) 2026 Mikhail Vasilev / MuroSync
 *
 *  License:
 *  This file is currently released under a restricted research license.
 *  Licensing terms may change in future revisions of the project.
 *
 *  Commercial use, redistribution, or integration into commercial products
 *  requires an explicit license agreement.
 *
 *  For licensing inquiries, please contact:
 *      info@murosync.com
 *
 *****************************************************************************/

#ifndef MUROSYNC_BUILD_INFO_H
#define MUROSYNC_BUILD_INFO_H

/* Product/version */
#define MUROSYNC_VERSION_MAJOR          1
#define MUROSYNC_VERSION_SUB            93
#define MUROSYNC_VERSION_CODE           65629UL

/* Build time (UTC) */
#define MUROSYNC_BUILD_UNIX_TIME        1780012006UL
#define MUROSYNC_BUILD_TIME_STR         "2026-05-28 23:46:46 UTC"

/* Optional: compile-time string helpers */
#define MUROSYNC_STR_IMPL(x)            #x
#define MUROSYNC_STR(x)                 MUROSYNC_STR_IMPL(x)
#define MUROSYNC_VERSION_STR            MUROSYNC_STR(1).MUROSYNC_STR(93)

#endif /* MUROSYNC_BUILD_INFO_H */
