@echo off
setlocal EnableExtensions

rem ============================================================================
rem  MuroSync - build info generator
rem  Generates: src\murosync_build_info.h
rem  State:     cmd\murosync_version_state.txt
rem ============================================================================

rem ---- Project identity / versioning policy ---------------------------------
set PRODUCT=MUROSYNC
set MAJOR=1

rem ---- Go to project root (parent of this cmd folder) ------------------------
cd /d %~dp0..

rem ---- Load previous state (if any) ------------------------------------------
set SUB=0
set OLDMAJOR=

if exist cmd\murosync_version_state.txt (
    for /f "tokens=1,2" %%a in (cmd\murosync_version_state.txt) do (
        set OLDMAJOR=%%a
        set SUB=%%b
    )
)

rem ---- Reset SUB if MAJOR changed --------------------------------------------
if "%OLDMAJOR%" NEQ "%MAJOR%" set SUB=0

rem ---- Bump SUB ---------------------------------------------------------------
set /a SUB=%SUB%+1

rem ---- Store state ------------------------------------------------------------
>cmd\murosync_version_state.txt echo %MAJOR% %SUB%

rem ---- Unix timestamp (UTC) ---------------------------------------------------
for /f %%a in ('powershell -NoProfile -Command "[int]([DateTimeOffset]::UtcNow.ToUnixTimeSeconds())"') do set TS=%%a

rem ---- Human-readable UTC time ------------------------------------------------
for /f "delims=" %%a in ('powershell -NoProfile -Command "(Get-Date).ToUniversalTime().ToString(\"yyyy-MM-dd HH:mm:ss 'UTC'\")"') do set TS_STR=%%a

rem ---- Compact version code: MAJOR*65536 + SUB --------------------------------
set /a VERCODE=%MAJOR%*65536+%SUB%

rem ---- Generate header --------------------------------------------------------
>src\murosync_build_info.h echo /******************************************************************************
>>src\murosync_build_info.h echo  *  Project    : MuroSync
>>src\murosync_build_info.h echo  *  File       : murosync_build_info.h
>>src\murosync_build_info.h echo  *  Created    : 2026-01-20
>>src\murosync_build_info.h echo  *  Author     : Mikhail Vasilev
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *  Description:
>>src\murosync_build_info.h echo  *  Auto-generated firmware build/version metadata.
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *  This file is generated by: cmd\gen_murosync_build_info.bat
>>src\murosync_build_info.h echo  *  Do not edit manually.
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *  Copyright (c) 2026 Mikhail Vasilev / MuroSync
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *  License:
>>src\murosync_build_info.h echo  *  This file is currently released under a restricted research license.
>>src\murosync_build_info.h echo  *  Licensing terms may change in future revisions of the project.
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *  Commercial use, redistribution, or integration into commercial products
>>src\murosync_build_info.h echo  *  requires an explicit license agreement.
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *  For licensing inquiries, please contact:
>>src\murosync_build_info.h echo  *      info@murosync.com
>>src\murosync_build_info.h echo  *
>>src\murosync_build_info.h echo  *****************************************************************************/
>>src\murosync_build_info.h echo.
>>src\murosync_build_info.h echo #ifndef MUROSYNC_BUILD_INFO_H
>>src\murosync_build_info.h echo #define MUROSYNC_BUILD_INFO_H
>>src\murosync_build_info.h echo.
>>src\murosync_build_info.h echo /* Product/version */
>>src\murosync_build_info.h echo #define MUROSYNC_VERSION_MAJOR          %MAJOR%
>>src\murosync_build_info.h echo #define MUROSYNC_VERSION_SUB            %SUB%
>>src\murosync_build_info.h echo #define MUROSYNC_VERSION_CODE           %VERCODE%UL
>>src\murosync_build_info.h echo.
>>src\murosync_build_info.h echo /* Build time (UTC) */
>>src\murosync_build_info.h echo #define MUROSYNC_BUILD_UNIX_TIME        %TS%UL
>>src\murosync_build_info.h echo #define MUROSYNC_BUILD_TIME_STR         "%TS_STR%"
>>src\murosync_build_info.h echo.
>>src\murosync_build_info.h echo /* Optional: compile-time string helpers */
>>src\murosync_build_info.h echo #define MUROSYNC_STR_IMPL(x)            #x
>>src\murosync_build_info.h echo #define MUROSYNC_STR(x)                 MUROSYNC_STR_IMPL(x)
>>src\murosync_build_info.h echo #define MUROSYNC_VERSION_STR            MUROSYNC_STR(%MAJOR%).MUROSYNC_STR(%SUB%)
>>src\murosync_build_info.h echo.
>>src\murosync_build_info.h echo #endif /* MUROSYNC_BUILD_INFO_H */

echo [%PRODUCT% BUILD] Version: %MAJOR%.%SUB%  (code %VERCODE%)
echo [%PRODUCT% BUILD] Build time: %TS_STR%
echo [%PRODUCT% BUILD] Unix time (UTC): %TS%

endlocal
